커뮤니티 관련 기능 서비스에 추가
project-lyrics/api-server pull request #32
Opened 2024-07-25 09:40 UTC by jinkonu

## 🔥 Task
- `Song`
  - 도메인 정의
  - 곡 제목 기반 검색 유스케이스 구현
&nbsp;
- `Note`
  - 도메인 정의
  - 노트 내 Lyrics 도메인 따로 정의
  - 노트 생성 유스케이스 구현
  - 사용자 별 노트 리스트 최신순 조회 유스케이스 구현
  - 사용자가 좋아하는 아티스트들과만 연관된 노트 리스트 최신순 조회 유스케이스 구현
  - 특정 아티스트와 연관된 노트 리스트 최신순 조회 유스케이스 구현
  - 노트 삭제 유스케이스 구현
  - 노트 수정 유스케이스 구현
&nbsp;
- `User`
  - 도메인 내 생성자에서 매개변수인 id를 복사하지 않는 버그 수정

## 🔊 Discussion
- MVC 계층의 request와 특정 유스케이스를 구현하기 위한 중간 도메인(SongCreate, NoteUpdate 등)을 따로 뒀습니다. 도메인 안에 MVC 레벨의 request이 들어오게 되어서 도메인이 request에 의존하게 되는 모습을 피하고 싶었습니다. 중간 도메인을 통해 생성, 수정 등의 행동을 도메인 안에 더 명확하게 나타낼 수 있을 것이라고 생각했습니다.
- 노트 수정 시에 원래 가사가 있던 노트에 가사를 수정하게 되면 기존 가사 데이터를 삭제하고 새롭게 가사 데이터를 삽입하고 있습니다. 이러한 방식에 대해서 괜찮으신지 궁금합니다.

&nbsp;

<img width="897" alt="image" src="https://github.com/user-attachments/assets/b795a9b8-3353-46cd-87df-9c6f6d9fa22e">

2024-07-26 05:57 UTC, wlsh44 requested changes
고생하셨습니다~
테스트 깨진거 확인해주시고 코멘트 남긴거에 관한 부분이랑 나중에 API까지 추가해서 머지하면 될 것 같아요

2024-07-26 05:59 UTC, wlsh44 commented on src/main/java/com/projectlyrics/server/domain/note/entity/Lyrics.java
> +    private Long id;
> 노트 수정 시에 원래 가사가 있던 노트에 가사를 수정하게 되면 기존 가사 데이터를 삭제하고 새롭게 가사 데이터를 삽입하고 있습니다. 이러한 방식에 대해서 괜찮으신지 궁금합니다.

말씀하신 이 부분과 같은 맥락인 것 같네요

2024-07-26 06:05 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/note/dto/request/NoteCreateRequest.java
> +        @Schema(name = "곡 ID")
제가 restdocs에 대한 배경지식이 부족했습니다...
혹시 restdocs를 통해서도 DTO에 대한 설명을 추가할 수 있을까요?

2024-07-26 06:09 UTC, wlsh44 commented
> * MVC 계층의 request와 특정 유스케이스를 구현하기 위한 중간 도메인(SongCreate, NoteUpdate 등)을 따로 뒀습니다. 도메인 안에 MVC 레벨의 request이 들어오게 되어서 도메인이 request에 의존하게 되는 모습을 피하고 싶었습니다. 중간 도메인을 통해 생성, 수정 등의 행동을 도메인 안에 더 명확하게 나타낼 수 있을 것이라고 생각했습니다.

MVC 계층은 ui 계층을 의미하는걸로 받아들여도 괜찮겠지요..? 저도 좋은 방식이라고 생각됩니다~

2024-07-26 06:13 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/song/dto/request/SongCreateRequest.java
> +public record SongCreateRequest(
후에 어드민을 통해 곡을 생성하는 경우가 있지 않을까 하여 정의해두었습니다...
삭제하는 게 좋을까요..?

2024-07-26 06:13 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/note/entity/Note.java
> +    public Note update(NoteUpdate noteUpdate) {
네 맞습니다!

2024-07-26 06:13 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/note/dto/request/NoteUpdateRequest.java
> +        Long publisherId
제가 API를 구현하지 않아서 미처 생각하지 못했습니다. 감사합니다!

2024-07-26 06:13 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/note/dto/request/NoteUpdateRequest.java
> +        Long noteId,
좋은 관점입니다! 수정하겠습니다

2024-07-26 06:13 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/note/entity/Note.java
> +    private static final long maxDraftNumber = 20;
아 죄송해요 ㅠ.ㅠ ... 처음에는 `@Value`를 통해 주입하려고 해서 카멜 케이스로 뒀는데,
static으로 주입할 방법을 찾지 못해 20을 직접 할당했고 변수명은 변경하지 않았네요..!

2024-07-26 06:13 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/note/entity/Lyrics.java
> +            return null;
만약 null을 리턴하지 않은 경우, 빈 값의 Lyrics 엔티티가 생성되었기 때문입니다..!

2024-07-26 06:13 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/note/entity/Lyrics.java
> +    private Long id;
처음에는 가사를 vo로 두고 개발했으나,
`User-TermsAgreement`와 유사하게 종속되지만 어떤 가사 개별적으로 사용할 확장성을 열어두고자 엔티티로 분리하게 되었습니다!

2024-07-26 06:13 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/note/dto/response/NoteGetResponse.java
> +                DomainUtils.formatTime(note.getCreatedAt()),
DomainUtils에 있는 다른 메서드처럼 `formatTime`도 createdAt이라는 도메인 내 필드를 다룬다고 생각하여 넣어두게 되었습니다. 그리고 NoteGetResponse가 아닌 다른 응답에서도 시간에 대해 넘겨줄 때 `formatTime`을 동일하게 사용해야 한다고 판단해 메서드를 정의하게 되었습니다..!

2024-07-26 07:44 UTC, wlsh44 commented on src/main/java/com/projectlyrics/server/domain/note/dto/request/NoteCreateRequest.java
> +        @Schema(name = "곡 ID")
넵 테스트 작성하실 때 같이 하시면 됩니다
기존 코드 참고해주세요

2024-07-26 08:21 UTC, wlsh44 commented on src/main/java/com/projectlyrics/server/domain/note/dto/response/NoteGetResponse.java
> +                DomainUtils.formatTime(note.getCreatedAt()),
그래서 응답에만 사용되는 코드이고 도메인을 위한 코드는 아니라고 생각이 되어서 조금 어색하게 느껴지는 것 같아요
프런트와 형식을 정한 이유는 그 값을 그대로 쓰기보다는(쓸 수도 있지만) 해당 포메팅을 이용해 객체로 받으려는 목적이 더 클 것 같다는 생각이 듭니다

2024-07-26 09:00 UTC, wlsh44 commented on src/main/java/com/projectlyrics/server/domain/note/entity/Note.java
> +    private static final long maxDraftNumber = 20;
static을 붙이면 @Value 주입이 안된다는건 저도 처음알았네요.. 단순히 값을 주입해주기 떄문에 될거라 생각했는데 스프링에서 코드로 막아놨네요. 덕분에 또 배워갑니다 ㅎㅎ
그리고 draftNumber를 @value로 주입하시려 했던 이유도 궁금합니다.  Note는 스프링에서 관리하는 bean이 아니기 때문에 @value가 동작하지 않을 것 같다는 생각도 들구요

2024-07-26 10:37 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/note/entity/Note.java
> +    private static final long maxDraftNumber = 20;
사실 단순하게 생각해서, 20이라는 최대 개수가 정책 변경으로 인해 수정될 가능성이 농후하기 때문에 좀 더 유동적으로 값을 바꿀 수 있도록 하고 싶었습니다!

2024-07-26 10:37 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/note/dto/response/NoteGetResponse.java
> +                DomainUtils.formatTime(note.getCreatedAt()),
그렇다면 `DomainUtils`에 두기보다는 일단은 `NoteGetResponse` 안에서만 처리를 하도록 할까요?

2024-07-26 10:37 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/note/dto/request/NoteCreateRequest.java
> +        @Schema(name = "곡 ID")
네 확인하겠습니다!

2024-07-29 03:53 UTC, wlsh44 requested changes
최근에 좀 바빠서 확인을 너무 늦게 했네요.. 죄송합니다
수정하신 부분 확인했고 질문 조금 남겼습니다
테스트 깨지는 거 수정했으니까 그거 pull 받아주시고 api 마저 개발해주시면 될 것 같아요. 고생하셨습니다!

2024-07-29 03:53 UTC, wlsh44 commented on src/main/java/com/projectlyrics/server/domain/song/dto/request/SongCreateRequest.java
> +        @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd", timezone = "Asia/Seoul")
`@JsonFormat`과 `@DateTimeFormat`을 같이 선언하신 이유가 있으실까요?

2024-07-29 03:53 UTC, wlsh44 commented on src/main/java/com/projectlyrics/server/domain/song/dto/request/SongCreateRequest.java
> +public record SongCreateRequest(
아뇨 그냥 궁금해서 여쭤봤습니다!
굳이 삭제는 하지 않아도 될 것 같아요

2024-07-29 03:53 UTC, wlsh44 commented on src/main/java/com/projectlyrics/server/domain/note/entity/Note.java
> +    public Note update(NoteUpdate noteUpdate) {
그럼 클라이언트에서 특정 값만 바꾸고 싶을 때는 나머지 값들을 다 null로 보내야 해서 이 부분이 조금 번거로워질 것 같은데 혹시 이렇게 구현하셨던 이유가 있으신가요?

2024-07-29 03:55 UTC, wlsh44 commented on src/main/java/com/projectlyrics/server/domain/note/dto/response/NoteGetResponse.java
> +                DomainUtils.formatTime(note.getCreatedAt()),
저는 그게 좀 더 나을 것 같다는 생각이 듭니다!

2024-07-29 07:56 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/song/dto/request/SongCreateRequest.java
> +        @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd", timezone = "Asia/Seoul")
이 부분 잘못된 것 같아요 수정하겠습니다!!

2024-07-31 07:45 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/note/entity/Note.java
> +    public Note update(NoteUpdate noteUpdate) {
나머지 값들을 선언하지 않아도 되지 않나요..?

2024-07-31 07:45 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/note/dto/response/NoteGetResponse.java
> +                DomainUtils.formatTime(note.getCreatedAt()),
반영하겠습니다~~~

2024-08-02 01:50 UTC, wlsh44 requested changes
고생하셨습니다!
모든 예외 상황에 대해서는 아니더라도 프런트에서 처리해야 할 예외에 관한 테스트 코드는 있으면 좋을 것 같아요 (note not found 같은..?)
그것만 추가하고 머지해도 될 것 같습니다

2024-08-02 01:50 UTC, wlsh44 commented on src/main/java/com/projectlyrics/server/domain/note/api/NoteController.java
> +    @GetMapping("/artists/{artistId}")
aritstId를 query string이 아닌 pathvariable로 두고 개발하신 이유가 있으신가요?

2024-08-07 05:28 UTC, merged