[SCRUM-166] 현재 사용자 인증 및 인가에 있어 admin 역할을 추가
project-lyrics/api-server pull request #45
Opened 2024-08-28 16:21 UTC by sebbbin

# 🍃 **Pull Requests**

## ⛳️ **작업한 스크럼**
- SCRUM - #166

## 👷 **작업한 내용**

해당 적혀있는 1,2,3업무에 대한 코드 작성을 완료하였습니다.
각 스탭별로 나눠서 커밋했습니다.
[admin 개발 업무](https://zircon-taste-62f.notion.site/0826-admin-e0ab5b2097ad44d1af4bc6be638e2d54?pvs=4)
-> 테스트 코드를 작성해서 테스트 해보면 좋을까요?

## 🚨 참고 사항

- 파일 위치 고민
`AdminInterceptor`에 위치를 고민하다가
1. `auth` -> `interceptor` (생성) -> `AuthInterceptor`,`AdminInterceptor` 두개 파일 넣기
2. (현재) `auth` -> `authentication` -> `AuthInterceptor` / `user` -> `authentication` -> `AdminInterceptor`
현재 2번인데 1번 어떤가요

(수빈) 개인적으로는 AdminInterceptor도 auth 폴더 안에 있는 것이 맞다고 생각합니다. 관련 의견 주시면 반영하겠습니다.

- ~~`AdminInterceptor`에서 `excludePathPatterns`을 추가할게 있을까요?~~ (url 관련 추가를 완료했습니다)

- ~~테스트 코드까지 코드의 간단한 부분은 수정하였는데 현재 gradle error가 나는 부분은 건들지 못했습니다 .. ;-;..~~-> 테스트 코드를 수정하고 현재 다 통과하는 것을 확인하였는데, github actions를 통과하지 못하는 상태인 것 같습니다.
---------------------------------
## 👷 **작업한 내용**

- 좋아요/북마크 중복 문제와 관련해서 동시성 관련한 테스트를 작성하고, `synchronized` 키워드를 활용해 해당 테스트를 통과할 수 있도록 코드를 작성했습니다.

## 🚨 참고 사항

- 로컬로나 실제 api 서버로나 확인해보았을 때는 중복 처리가 제대로 작동하고 있었습니다. 만약 문제 발생의 원인이 동시성 관련 문제가 아니라면 다시 문제를 살펴보아야 할 것 같습니다.
-  `synchronized` 키워드로 문제를 해결하기는 했지만, 후에 서버를 확장해서 분산 서버의 형태가 된다면, 동기화 처리가 제대로 되지 못합니다. 혹시 redis를 활용한 분산락 처리까지 고려하는 것이 좋을지 궁금합니다.
- 물론 어플리케이션 단에서 좋아요/북마크 중복 처리를 막을 수 있지만 데이터베이스 단에서 트리거를 활용하면 중복 데이터가 생기는 문제를 추가로 방지할 수 있습니다. 데이터베이스에 트리거를 추가하는 것에 대해서는 어떻게 생각하시는지 궁금합니다.
```sql
CREATE TRIGGER before_insert_bookmark
BEFORE INSERT ON lyrics.bookmarks
FOR EACH ROW
BEGIN
  IF (NEW.deleted_at IS NULL AND
      EXISTS (SELECT 1 FROM lyrics.bookmarks WHERE user_id = NEW.user_id AND note_id = NEW.note_id AND deleted_at IS NULL)) THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Duplicate entry for active bookmark';
  END IF;
END;
```

2024-09-01 08:42 UTC, jinkonu requested changes
말씀드린 부분을 깔끔하게 구현하신 것 같습니다!!
고생 많으셨고, 리뷰드린 부분에 대해 참고부탁드려요~~~
화이팅

2024-09-01 08:42 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/bookmark/service/BookmarkCommandService.java
> +    public synchronized Bookmark create(Long noteId, Long userId) {
간단명쾌한 답이네요!!

2024-09-01 08:42 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/user/authentication/AdminInterceptor.java
> +}
굿!! 잘짜신 것 같아요

2024-09-01 08:42 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/global/configuration/WebConfig.java
> +                .excludePathPatterns("/api/v1/artists/search");
이렇게 되는 경우에 `/api/v1/artists/search`가 인터셉터 범위에서 제외되는 것을 확인했는지 궁금합니다!

2024-09-01 08:42 UTC, jinkonu commented on src/test/java/com/projectlyrics/server/domain/bookmark/service/BookmarkCommandServiceTest.java
> +        for (int i = 0; i < threadCount; i++) {
for 반복문은 말그대로 반복해서 코드를 실행하지 않나요?
바로 밑의 `execute`를 동시에 실행하지 않을 수도 있을 것 같은데 테스트는 정상적으로 통과하는지 궁금합니다...

저는 이 부분이 의심되어서 챗지피티에 문의하니까 아래와 같은 코드를 주더라고요!! 참고 부탁드립니다..!
``` java
@Test
void 북마크가_동시다발적으로_저장될_떄도_중복_북마크가_생기지_않아야_한다() {
    //given
    int threadCount = 100;
    ExecutorService executorService = Executors.newFixedThreadPool(threadCount);
    CountDownLatch readyLatch = new CountDownLatch(threadCount);
    CountDownLatch startLatch = new CountDownLatch(1);
    CountDownLatch doneLatch = new CountDownLatch(threadCount);
    AtomicInteger duplicateErrorCount = new AtomicInteger(0);

    //when
    for (int i = 0; i < threadCount; i++) {
        executorService.execute(() -> {
            readyLatch.countDown(); // 스레드가 준비 상태임을 알림
            try {
                startLatch.await(); // 모든 스레드가 준비될 때까지 대기
                sut.create(note.getId(), user.getId());
            } catch (BookmarkAlreadyExistsException | NonUniqueResultException e) {
                duplicateErrorCount.getAndIncrement();
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            } finally {
                doneLatch.countDown();
            }
        });
    }

    try {
        readyLatch.await(); // 모든 스레드가 준비될 때까지 대기
        startLatch.countDown(); // 모든 스레드가 동시에 실행 시작
        doneLatch.await(); // 모든 스레드의 실행이 끝날 때까지 대기
    } catch (InterruptedException e) {
        Thread.currentThread().interrupt();
        throw new RuntimeException(e);
    }

    //then
    assertAll(
        () -> assertThat(bookmarkQueryRepository.findByNoteIdAndUserId(note.getId(), user.getId())).isPresent(),
        () -> assertThat(duplicateErrorCount.get()).isEqualTo(threadCount - 1)
    );
}
```

2024-09-01 15:44 UTC, elive7 commented on src/main/java/com/projectlyrics/server/global/configuration/WebConfig.java
> +                .excludePathPatterns("/api/v1/artists/search");
네 로컬에서 통해 확인해보았습니다! 사진과 같이 아티스트 추가는 막히는 대신에, 아티스트 검색은 제대로 작동합니다~
![image](https://github.com/user-attachments/assets/197116b1-7f5c-49d1-9fea-aad4f392c988)
![image](https://github.com/user-attachments/assets/95c14b07-76db-4961-8122-fe15436d2af7)

2024-09-01 15:45 UTC, elive7 commented on src/test/java/com/projectlyrics/server/domain/bookmark/service/BookmarkCommandServiceTest.java
> +        for (int i = 0; i < threadCount; i++) {
오 제가 참고한 동시성 테스트에서는 주로 for문이나 repeat문을 썼었는데 확실히 한번에 execute하면 동시성 테스트를 더 엄격하게 할 수 있을 것 같아요! 감사합니다~~

2024-09-02 03:59 UTC, jinkonu commented on src/test/java/com/projectlyrics/server/domain/bookmark/service/BookmarkCommandServiceTest.java
> +        for (int i = 0; i < threadCount; i++) {
👍👍

2024-09-02 03:59 UTC, jinkonu approved these changes

2024-09-02 12:04 UTC, merged