신고 기능 개발
project-lyrics/api-server pull request #46
Opened 2024-09-08 11:17 UTC by elive7

# 🍃 **Pull Requests**

## ⛳️ **작업한 브랜치**
- SCRUM-172

## 👷 **작업한 내용**
- Report 도메인 개발
- 신고 생성 및 승인 로직 추가 (service, controller)
- 신고 생성 및 승인 관련 테스트 작성
------
- slack 연동 중.... (코드 추가 예정)

## 🚨 참고 사항

- 어차피 신고 승인과 같은 슬랙으로 진행하는 api에 대해서는 컨트롤러 테스트를 작성할 필요가 있을지 궁금합니다...
- 또한 같은 신고 작성자&대상이 이미 존재하여 신고 사유가 업데이트되는 경우에는 ***승인여부와 허위신고여부도 원상복귀하는 로직***으로 구현했는데 이 부분을 어떻게 해야 할지도 고민이네요...
![image](https://github.com/user-attachments/assets/90412d28-1aa2-4e59-9ab0-98fef8b68fc3)
- 현재 구상하고 있는 slack UI 입니다. 혹시 허위신고 버튼을 누른다면 승인 여부는 자연스럽게 dismiss로 되는 것이 맞을까요? 현재 코드에서는 (승인여부, 허위신고여부)를 한꺼번에 받아야 하기에 여쭤봅니다.
- 또한 원래 신고 대상 노트/댓글의 작성자 id를 보여줄 수 있는 view을 기획측에 제공하자고 했었는데 slack에서 다음과 같이 보여주면 굳이 뷰를 만들지 않아도 되지 않을까요...?
-  <U>승인으로 변경한 경우, 신고 id를 응답으로 반환해서 admin이 조치 저장 시에 활용할 수 있도록 해야 한다.<U>
-  일단은 이렇게 구현을 했는데 admin이 조치 저장시에 신고 id를 어떻게 활용할지 궁금합니다.

2024-09-08 11:41 UTC, jinkonu requested changes
화이팅~~~
수정하시면 또 리뷰할게요

2024-09-08 11:41 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/report/domain/Report.java
> +                  @Nullable String email) {
`@Nullable`가 없어도 null 값이 잘 돌아가는지 확인하고, 만약 돌아간다면 지워주셔도 좋을 것 같아요

2024-09-08 11:41 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/report/domain/Report.java
> +    }
다른 도메인과 컨벤션을 맞춰준 것은 좋지만,
사실 아래 create와 createWithId에서 id 매개변수에 null을 직접 넣으면 얘는 필요가 없더라고요!

2024-09-08 11:41 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/report/domain/Report.java
> +    }
이런 도메인 행동들을 도메인 안에 넣어주신 건 좋은 선택인 것 같아요!! 굿 🥹🥹

2024-09-08 11:41 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/report/domain/ReportCreate.java
> +        String email
Nullable이 없이 null 필드로 ReportCreate를 만들 수 있지 않나요? 
그리고 반대로 Nullable이 있다고 하더라도 NullPointerException을 피할 수는 없을 거에요 ... 제가 @Nullable 소스코드 읽었을 때에는 코드를 읽는 사람을 위한 편의로서의 기능 말고는 없는 것 같아서 ... 제가 틀렸다면 알려주세요~~~

2024-09-08 11:41 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/report/dto/request/ReportCreateRequest.java
> +        @Nullable
여기도 마찬가지입니다!

2024-09-08 11:41 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/report/service/ReportCommandService.java
> +                .orElse(null);
이 부분을 `if(Objects.nonNull(request.commentId))`로 처리하는 게 어떨까요? 요청의 commentId가 null이라고 하더라도 findById를 호출하게 되지 않을까 해서요!

2024-09-08 11:41 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/report/service/ReportCommandService.java
> +        report.resolve(ReportResolve.of(reportResolveRequest.approvalStatus(), reportResolveRequest.isFalseReport()));
ReportCreate와 달리 ReportResolve를 생성하는 데에는 ReportResolveRequest로 충분하기 때문에 파라미터를 request의 필드가 아닌, request 자체로 하는 게 어떤가 싶네요!

2024-09-08 11:41 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/global/handler/GlobalExceptionHandler.java
> +
감사합니다~~~

2024-09-09 11:00 UTC, elive7 commented on src/main/java/com/projectlyrics/server/domain/report/domain/ReportCreate.java
> +        String email
찾아보니 맞는 것 같아요
@Nullable은 다 제거하도록 하겠습니다!

2024-09-09 11:01 UTC, elive7 commented on src/main/java/com/projectlyrics/server/domain/report/domain/Report.java
> +    }
오호 좋은 것 같아요! 그렇게 수정하겠습니당

2024-09-09 11:07 UTC, elive7 commented on src/main/java/com/projectlyrics/server/domain/report/service/ReportCommandService.java
> +        report.resolve(ReportResolve.of(reportResolveRequest.approvalStatus(), reportResolveRequest.isFalseReport()));
네 그렇게 수정하겠습니다!

2024-09-09 11:41 UTC, elive7 commented on src/main/java/com/projectlyrics/server/domain/report/service/ReportCommandService.java
> +                .orElse(null);
저도 이번에 알게 된 것인데 Optional.map 메서드는 Optional 객체가 값을 포함하고 있을 때만 지정된 함수를 호출한다고 해요! 즉, Optional이 빈 상태(값이 없거나 null인 경우)일 때는 함수를 호출하지 않아요!
request.commentId()가 null인 경우에는 Optional.ofNullable(null) -> 빈 Optional이고, map 함수가 호출 안 되어 orElse(null)을 실행해 결과는 null이 됩니다!

실제로 postman으로 실행해봤을 때도 문제되지 않았어요!

2024-09-09 14:58 UTC, jinkonu approved these changes
고생하셨어용

2024-09-09 14:58 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/auth/authentication/interceptor/SlackInterceptor.java
> +            return calculatedSignature.equals(signature);
이 검증 로직에 대한 레퍼런스는 어디서 구하셨는지 궁금합니다~~~

2024-09-09 14:58 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/report/domain/ReportCreate.java
> +
빈 줄 필요없지 않을까요?!

2024-09-09 14:58 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/report/service/ReportCommandService.java
> +                .orElse(null);
오 좋네용 그러면 그냥 지금 그대로 가도 좋겠네용

2024-09-09 14:58 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/report/repository/impl/QueryDslReportQueryRepository.java
> +                        .selectFrom(report)
SlackClient를 보고 알게 된 건데,
메서드를 통해 조회한 report에서 100% 참조하게 되는 다른 객체(Reporter, Note 등)를 fetch join해야 N+1 문제를 방지할 수 있습니다.

2024-09-09 14:58 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/global/slack/SlackClient.java
> +    }
이 부분은 개인적으로 두 메서드간 중복이 많기 때문에 리팩토링을 한 번 고려해주시면 좋을 것 같아요!

2024-09-09 14:58 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/global/slack/api/SlackController.java
> +    }
이 부분도 일단은 잘 작성하셨는데, 후에 리팩토링 한 번 해봅시다!

2024-09-11 05:41 UTC, elive7 commented on src/main/java/com/projectlyrics/server/domain/auth/authentication/interceptor/SlackInterceptor.java
> +            return calculatedSignature.equals(signature);
https://api.slack.com/authentication/verifying-requests-from-slack 
위 슬랙 공식 문서와 아래 블로그를 참고해서 작성했습니다~
https://velog.io/@tae2089/Slack-Secret-Signature-%EC%9B%90%EB%A6%AC-%EB%B0%8F-%EC%BD%94%EB%93%9C-%EC%9E%91%EC%84%B1%EB%B2%95with-Golang

2024-09-11 05:41 UTC, elive7 commented on src/main/java/com/projectlyrics/server/domain/report/repository/impl/QueryDslReportQueryRepository.java
> +                        .selectFrom(report)
감사합니다. 수정했습니다!

2024-09-11 05:41 UTC, elive7 commented on src/main/java/com/projectlyrics/server/global/slack/SlackClient.java
> +    }
리팩토링을 진행해 다시 커밋했습니다!!

2024-09-11 05:42 UTC, elive7 commented on src/main/java/com/projectlyrics/server/global/slack/api/SlackController.java
> +    }
넵 일단은 냅두고 후에 리팩토링 해보겠습니당...

2024-09-11 06:33 UTC, jinkonu approved these changes
딱 하나만 마지막으로 해주시고 바로 머지해주세요~~~

2024-09-11 06:33 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/global/slack/SlackClient.java
> +    private void sendReportMessage(Report report, String contentType, Long contentId, String content) {
private 메서드를 최하단으로 옮겨주세요!

2024-09-11 07:52 UTC, merged