조치 기능 개발
project-lyrics/api-server pull request #50
Opened 2024-10-06 12:36 UTC by elive7

# 🍃 **Pull Requests**

## ⛳️ **작업한 브랜치**
- [SCRUM-175]
-
## 👷 **작업한 내용**

- 조치 기능 개발
- 강제 탈퇴 로직 구현 및 회원 가입시 강제 탈퇴 이력 조회
- 글 작성 제한 조치가 적용된 사용자는 글 작성 못하도록 수정
- 조치시 알림 기능 개발
- 테스트 작성

## 🚨 참고 사항

- 아직 알림 문구가 픽스되지 않았기 때문에 후에 수정이 필요할 것 같습니다.
- 기존에 실패하던 알림 테스트 수정해서 되게 만들어놨습니다! (안되면 되도록...) 하지만 아직도 중복 관련 동시성 테스트는 해결하지 못했어요

2024-10-07 06:29 UTC, jinkonu requested changes
테스트 같은 경우엔 다시 살펴보면서 천천히 확인하겠습니다!
정말 고생 많으셨고, 리뷰 확인 부탁드리겠습니다~~~
🥹🥹

2024-10-07 06:29 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/notification/service/NotificationCommandService.java
> +    }
CompletableFuture를 반환타입에 추가하게 된 이유가 있을까요? (진짜 모름)

2024-10-07 06:29 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/report/dto/request/ReportCreateRequest.java
제가 뒤늦게 발견한 부분이 있는데요!
컨트롤러에서 바로 `ReportReason`을 매핑할 수 있을지에 대해 고민이 필요할 것 같아요.
`ReportReason`은 문자열이 아니라 enum이기 때문에 HTTP 요청이 컨트롤러 메서드 매개변수로 들어가기 이전에 변환이 필요할 거에요.
`ProfileCharacterConverter`를 참고하면 도움이 될 겁니다!

2024-10-07 06:29 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/user/repository/impl/QueryDslUserQueryRepository.java
> +                        .fetchOne()
여기서도 `Discipline` 리포지토리에서처럼 fetchFirst를 사용해도 좋을 것 같아요!

2024-10-07 11:03 UTC, elive7 commented on src/main/java/com/projectlyrics/server/domain/like/repository/LikeQueryRepository.java
> +    @Lock(LockModeType.PESSIMISTIC_WRITE)
이거 코드를 지웠어야 했는데,,, 잘못해서 들어갔네요 다시 빼도록 하겠습니다!

2024-10-07 11:06 UTC, elive7 commented on src/main/java/com/projectlyrics/server/domain/discipline/exception/InvalidDisciplineCreate.java
> +public class InvalidDisciplineCreate extends FeelinException {
헉 저도 exception으로 끝나는 게 맞는 것 같아요 고치겠습니다!!

2024-10-07 11:21 UTC, elive7 commented on src/main/java/com/projectlyrics/server/domain/user/repository/impl/QueryDslUserQueryRepository.java
> +                        .fetchOne()
네 그렇게 수정하겠습니다!

2024-10-07 11:22 UTC, elive7 commented on src/main/java/com/projectlyrics/server/domain/discipline/repository/DisciplineQueryRepository.java
> +    Boolean existsDisciplineOfArtist(Long artistId, Long userId);
네 그렇게 수정할게요! 컨벤션 맞춰서 by를 넣었습니당

2024-10-07 11:24 UTC, elive7 commented on src/main/java/com/projectlyrics/server/domain/discipline/exception/InvaildDisciplineAction.java
헉 바로 고칠게요!

2024-10-07 11:32 UTC, elive7 commented on src/main/java/com/projectlyrics/server/domain/discipline/service/DisciplineCommandService.java
> +                .orElse(null);
artistId가 null로 들어올 경우를 대비해서 그렇게 작성했는데 다른 코드를 보니 artistId가 null로 들어오는 경우는 없을 것 같아서 ofNullable로 감싸는 코드는 삭제했습니다!

2024-10-07 11:37 UTC, elive7 commented on src/main/java/com/projectlyrics/server/domain/discipline/service/DisciplineCommandService.java
> +            user.forcedWithdrawal(Clock.systemDefaultZone());
저도 그 방법을 생각해보았는데, 다른 서비스단에서는 레포지토리만 참조하고 있는데 DisciplineCommandService에서 AuthCommandService을 참조하게 되는 것이 조금 걸려서요.., 그렇다고 하더라도 AuthCommandService에서 작성하는 것이 좋을까요?

2024-10-07 11:45 UTC, elive7 commented on src/main/java/com/projectlyrics/server/domain/notification/service/NotificationCommandService.java
> +    }
이 부분은 테스트랑 관련이 있는데요!
```
@Test
    void 댓글에_대한_알림을_저장한다() throws Exception {
        // given
        given(firebaseMessaging.send(any())).willReturn(null);
        CommentEvent commentEvent = CommentEvent.from(comment);

        // when
        sut.createCommentNotification(commentEvent);

        // then
        List<Notification> result = notificationQueryRepository.findAllByReceiverId(user.getId(), null, PageRequest.ofSize(10))
                .getContent();

        assertAll(...)
    }
 ```
계속 test 시 실패해서 주석처리해놓았던,,,, 테스트입니다. 

알아보니 Async를 통해 비동기로 create를 하고 findAllByReceiverId를 하게 되는데 create를 하기 전에 findBy 함수를 호출하면서 result에 빈 값이 담기는 것이라고 하더라고요! 

만약 CompletableFuture를 사용하면 sut.createCommentNotification(commentEvent).get();을 통해 create가 끝날 때까지 기다린 후에 findBy를 할 수 있다고 합니다! 저도 이번에 알게 되었어요

2024-10-07 11:46 UTC, elive7 commented on src/main/java/com/projectlyrics/server/domain/common/entity/BaseEntity.java
> +        this.deletedBy = 0L;
admin의 user_id 그냥 1로 하드코딩해도 되나요...?

2024-10-07 11:55 UTC, elive7 commented on src/main/java/com/projectlyrics/server/domain/report/dto/request/ReportCreateRequest.java
ProfileCharacterConverter 찾아보았는데요!
제가 확인해보았을 때는 포스트맨에서도 제대로 작동했고 (아래 사진 참고)  또 gpt한테 물어보니 아래와 같은 답변을 받아서요! 혹시 그래도 converter가 필요할까요..?

> @RequestBody 어노테이션을 사용할 때도 enum 값이 포함된 JSON 데이터가 컨트롤러 메서드로 전달될 경우, 자동으로 변환이 이루어질 수 있습니다. Spring에서는 Jackson 라이브러리를 사용하여 JSON을 객체로 변환하는데, 이 과정에서 enum 값 역시 자동으로 변환됩니다.
> 
> 기본 동작
> @RequestBody는 요청 본문을 Java 객체로 매핑하는 역할을 합니다. 만약 매핑할 객체에 enum 타입이 포함되어 있다면, Spring의 Jackson 라이브러리가 JSON의 문자열 값을 해당 enum 값으로 변환합니다.
> 

![image](https://github.com/user-attachments/assets/874934a9-ca00-4b29-a829-6bf3443308cc)

2024-10-07 12:51 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/discipline/service/DisciplineCommandService.java
> +                .orElse(null);
넵!

2024-10-07 13:06 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/discipline/service/DisciplineCommandService.java
> +            user.forcedWithdrawal(Clock.systemDefaultZone());
순환참조가 있는 것 같지는 않은데
도메인의 개념상 애매해질 것 같다는 뜻일까요?

2024-10-07 13:07 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/user/repository/impl/QueryDslUserQueryRepository.java
> +                        .fetchOne()
🥹🥹

2024-10-07 13:42 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/report/dto/request/ReportCreateRequest.java
그러네요 ...
그러면 굳이 할 필요는 없을 것 같아요!

2024-10-07 13:43 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/notification/service/NotificationCommandService.java
> +    }
오 그러면 근본적으로 테스트가 잘못되었던 거네요 ...
감사합니다!

2024-10-07 13:44 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/discipline/exception/InvalidDisciplineCreate.java
> +public class InvalidDisciplineCreate extends FeelinException {
🥹🥹

2024-10-09 13:43 UTC, elive7 commented on src/main/java/com/projectlyrics/server/domain/discipline/service/DisciplineCommandService.java
> +            user.forcedWithdrawal(Clock.systemDefaultZone());
네 그랬는데 그냥 이번에 authCommandService로 빼는 방식으로 수정했어요!

2024-10-10 07:35 UTC, jinkonu approved these changes
고생 정말 많으셨어요!!

2024-10-10 08:43 UTC, sebbbin approved these changes
고생많으셨습니다 :-)

2024-10-10 08:43 UTC, sebbbin commented on src/main/java/com/projectlyrics/server/domain/common/entity/BaseEntity.java
> +    @Value("${admin}")
굿 😊

2024-10-10 08:43 UTC, sebbbin commented on src/main/java/com/projectlyrics/server/domain/discipline/domain/Discipline.java
> +    }
이렇게가 슬랙에서 입력받는 포맷인건가요 ?!

2024-10-10 08:43 UTC, sebbbin commented on src/main/java/com/projectlyrics/server/domain/discipline/exception/InvalidDisciplineCreateException.java
> +        super(ErrorCode.INVALID_DISCIPLINE_CREATE);
feelin의 코드 컨벤션일수도 있지만,, errorcode 한개를 단독으로 사용하는 exception을 따로 분리해둔 이유가 있을까요?

2024-10-11 16:55 UTC, elive7 commented on src/main/java/com/projectlyrics/server/domain/discipline/domain/Discipline.java
> +    }
아뇨 기획분들이 {시작시간}이라고 입력했을 때 실제 시작시간으로 변경하는 로직입니다!

2024-10-11 16:56 UTC, elive7 commented on src/main/java/com/projectlyrics/server/domain/discipline/exception/InvalidDisciplineCreateException.java
> +        super(ErrorCode.INVALID_DISCIPLINE_CREATE);
흠... 컨벤션도 컨벤션이지만 코드상에서 exception만 보더라도 어떤 에러인지 더 상세하게 알 수 있게 함이 아닐까 싶어요... 정답은 없는 것 같아요

2024-10-11 17:30 UTC, merged