사용자 카카오 소셜 로그인 API 구현
project-lyrics/api-server pull request #6
Opened 2024-04-22 08:06 UTC by jinkonu

# 🔥 Task
- feign으로 카카오 API 접근하여 사용자 정보 조회하는 소셜 서비스 구현
- Redis를 활용하여 리프레쉬 토큰 관리하고, 액세스 토큰 발급하는 jwt 로직 구현
- socialId 기반으로 사용자 조회하고, 없을 경우 생성하고 토큰 발급하여 반환하는 사용자 API 구현

&nbsp;
&nbsp;

# 📝 Question
- 테스트를 작성해야 하는데, 인가 코드를 발급하는 것을 테스트로 어떻게 구현해야 할지 고민입니다...
- Redis를 통해 리프레쉬 토큰을 관리하도록 작성했는데, 이 부분에 대한 의견을 듣고 싶습니다!

2024-04-22 22:20 UTC, mongmeo-dev requested changes
고생하셨습니다.
코멘트 확인해주시고, 이해 안 되는 부분 있으시면 언제든 연락주세요.

추가로, JWT의 refresh token을 redis에 저장하고 있는데, 이렇게 되면 session base authentication과의 차이점이 모호해지는데 이에 대해 고민해보셨으면 해요~!

2024-04-22 22:20 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/server/domain/user/api/UserController.java
> +  public ResponseEntity<LoginResponse> login(
ResponseBody를 한 번 더 감싸는 공통 응답 포맷이 있었으면 합니다~

2024-04-22 22:20 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/server/domain/user/api/UserController.java
> +        .status(HttpStatus.CREATED)
이거, ResponseEntity로 status code 지정하면 Swagger 설정(`@Operation`)에도 응답 코드 넣어주셔야해요~

2024-04-22 22:20 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/server/domain/user/dto/response/LoginResponse.java
> +  }
요정도는 생성자로 처리해도 될 것 같은...!느낌이네여

2024-04-22 22:20 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/server/domain/user/entity/User.java
> +  }
auth provider에 대한 내용은 별도의 테이블로 분리되었으면 합니다~!

2024-04-22 22:20 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/server/domain/user/repository/CommandQueryUserRepository.java
> +public interface CommandQueryUserRepository extends Repository<User, Long>, QueryUserRepository {
구현체도 Command, Query가 분리되었으면 해요~
`JpaCommandUserRepository`, `QueryDslQueryUserRepository` 같은 이름으로요~~

2024-04-22 22:20 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/server/domain/user/repository/QueryUserRepositoryImpl.java
> +public class QueryUserRepositoryImpl implements QueryUserRepository {
`QueryDslQueryUserRepository` 정도는 어떨까요?!
+.. 이거 `@Repository` 어노테이션 붙여주셔야해요!

2024-04-22 22:20 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/server/domain/user/repository/QueryUserRepositoryImpl.java
> +  public Optional<User> findBySocialIdAndAuthProviderAndNotDeleted(Long socialId, AuthProvider authProvider) {
socialId가 필수값이라면, Long이 아닌 long으로 받아도 될 것 같네요~

2024-04-22 22:20 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/server/domain/user/service/UserCommandService.java
> +}
엇 이거 인터페이스는 `application/usecase/{command|query}/~UseCase`로 갔으면 합니다~!

2024-04-22 22:20 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/server/domain/user/service/impl/UserCommandServiceImpl.java
> +public class UserCommandServiceImpl implements UserCommandService {
`Impl` Suffix는 최대한 지양해주세요..!

2024-04-22 22:20 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/server/domain/user/service/impl/UserCommandServiceImpl.java
> +        throw new BusinessException(ErrorCode.BAD_REQUEST);
이 걸 위한 ErrorCode를 만드셨음 합니다!

2024-04-22 22:20 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/server/domain/user/service/impl/UserCommandServiceImpl.java
> +}
사실, 메서드를 나누신 기준을 잘 모르겠습니다..!
단순히 코드가 길어져서 나눈 것 같아요.

`getAccessAndRefreshTokens`라는 메서드는 access토큰과 refresh 토근만을 제공할 것 같지만, 실제로는 회원가입까지 하고 있어요. 

코드가 거짓말을 해서는 안됩니다. 의도를 숨겨서도 안 되구요.
단순히 길어지는 코드를 줄이기 위해 메서드화를 하기 보다는 맥락에 따라 나누셨으면 해요.
이 때문에 중복이 생기더라도요.

2024-04-22 22:20 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/server/global/auth/external/dto/request/UserLoginRequest.java
> +    @Schema(name = "인가 코드 값")
name 말고 description 값으로 주세욥!

2024-04-22 22:21 UTC, mongmeo-dev commented
> 📝 Question
> 테스트를 작성해야 하는데, 인가 코드를 발급하는 것을 테스트로 어떻게 구현해야 할지 고민입니다...
> Redis를 통해 리프레쉬 토큰을 관리하도록 작성했는데, 이 부분에 대한 의견을 듣고 싶습니다!

이에 대한 답변을 드리자면
1. 테스트에 집착하지 않으셔도 됩니다. 복잡한 비즈니스 로직만 작성해도 충분해요.
2. 요건 더 고민해보셨으면 합니다~ 더 고민해보시고 저에게 말씀해주세요!

2024-04-23 05:21 UTC, jinkonu commented on build.gradle
> +    implementation group: 'io.jsonwebtoken', name: 'jjwt-jackson', version: '0.11.5'
네 맞추겠습니다 ~~~

2024-04-23 05:21 UTC, jinkonu commented on build.gradle
> +    implementation "org.springframework.cloud:spring-cloud-starter-openfeign"
Spring MVC에서 제공하는 어노테이션을 쓸 수도 있고, 작성했을 때 가독성이 괜찮은 것 같아 선택했습니다! 혹시 추천하는 선택지가 있다면 말씀해주세요!

2024-04-23 05:21 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/ServerApplication.java
> +@EnableFeignClients
네 알겠습니다!

2024-04-23 05:21 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/user/api/UserController.java
> +  public ResponseEntity<LoginResponse> login(
그러면 공통 응답 포맷은 UserController뿐만 아니라, 모든 컨트롤러 계층에서 사용할 수 있도록 SuccessResponse로 지어서 해도 괜찮을까요?

2024-04-23 05:22 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/user/api/UserController.java
> +        .status(HttpStatus.CREATED)
네 바로 추가하겠습니다!

2024-04-23 05:28 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/user/api/UserController.java
> +        .status(HttpStatus.CREATED)
![image](https://github.com/project-lyrics/api-server/assets/137763434/645cf4ef-a54a-4e6f-a5d5-849cb78c1ab1)
![image](https://github.com/project-lyrics/api-server/assets/137763434/fd5ed50c-536f-4bee-b330-d64ac681ea5f)
혹시 위 사진처럼 Swagger를 위한 코드를 인터페이스에 따로 빼는 패턴을 활용하는 건 어떠세요?

2024-04-23 05:30 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/user/dto/response/LoginResponse.java
> +  }
네 생성자와 동일한 역할을 하니 불필요한 것 같네요 ㅠㅠ 고치겠습니다~~

2024-04-23 05:35 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/user/entity/User.java
> +  }
enum 타입용 테이블을 생성하라는 말씀이실까요??

2024-04-23 05:39 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/user/repository/CommandQueryUserRepository.java
> +public interface CommandQueryUserRepository extends Repository<User, Long>, QueryUserRepository {
네 최대한 제가 의도를 이해한 방향으로 수정하겠습니다 !

2024-04-23 05:41 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/user/repository/QueryUserRepositoryImpl.java
> +public class QueryUserRepositoryImpl implements QueryUserRepository {
네 훨씬 나은 네이밍인 것 같습니다!!
(아티스트쪽도 현재 Impl로 구현체 이름을 붙이고 있어서, 이 부분도 나중에 제가 수정해야 할 것 같습니다!)

2024-04-23 05:42 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/user/repository/QueryUserRepositoryImpl.java
> +  public Optional<User> findBySocialIdAndAuthProviderAndNotDeleted(Long socialId, AuthProvider authProvider) {
네 습관적으로 래퍼 클래스로 적었네요 ㅠㅠ 감사합니다

2024-04-23 05:45 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/user/service/UserCommandService.java
> +}
![image](https://github.com/project-lyrics/api-server/assets/137763434/7f15bf89-da41-4eff-93e2-379f5f48d0bb)

패키지 구조를 말씀하신거죠??
혹시 위 사진을 예로 든다면 'application'은 어떤 디렉토리에 해당할까요?

2024-04-23 08:04 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/user/service/impl/UserCommandServiceImpl.java
> +        throw new BusinessException(ErrorCode.BAD_REQUEST);
반영하겠습니다 !!

2024-04-23 08:05 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/user/service/impl/UserCommandServiceImpl.java
> +public class UserCommandServiceImpl implements UserCommandService {
service - serviceImpl 대신에 usecase - interactor 로 변경해봤습니다!

2024-04-23 08:06 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/user/service/impl/UserCommandServiceImpl.java
> +}
아이고 ... 제 치부가 드러났군요 하하...
철저하게 리팩토링해보겠습니다!

2024-04-23 08:06 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/global/auth/external/dto/request/UserLoginRequest.java
> +    @Schema(name = "인가 코드 값")
반영했습니다!

2024-04-23 08:06 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/global/auth/external/dto/response/UserInfoResponse.java
> +  }
아닙니다 ㅠㅠ 가독성 때문에 습관처럼 사용했습니다. 
다른 코멘트와 동일하게 생성자로 변경했습니다!

2024-04-23 08:06 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/global/auth/external/kakao/KakaoApiClient.java
> +}
반영했습니다!

2024-04-23 08:07 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/global/auth/external/kakao/dto/KakaoAccessTokenResponse.java
> +@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
클라이언트와 상호작용 시에 카멜케이스-스네이크케이스 호환을 위해 적용했습니다!

2024-04-23 08:07 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/global/auth/jwt/JwtTokenProvider.java
> +  private static final Long REFRESH_TOKEN_EXPIRATION_TIME = 60 * 60 * 24 * 1000L * 14;
제 실수입니다 ㅠㅠ 기본형 타입으로 변경했습니다!

2024-04-24 04:01 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/user/repository/CommandQueryUserRepository.java
> +public interface CommandQueryUserRepository extends Repository<User, Long>, QueryUserRepository {
제가 말씀해주신 대로 수정을 시도했는데,
QueryDsl에서 구현체를 찾는 방식 자체가 `인터페이스명 + "Impl" suffix`이다보니 한계가 있네요...
`QueryDslQueryUserRepository`처럼 앞에 구현체의 특징을 쓰는 방식은 힘들 것 같아요 ... ㅠㅠ

2024-04-24 04:02 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/server/domain/user/api/UserController.java
> +  public ResponseEntity<LoginResponse> login(
넵~!

2024-04-24 04:02 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/server/domain/user/api/UserController.java
> +        .status(HttpStatus.CREATED)
흠...나쁘진 않은데 안 귀찮으시겠나욤?

2024-04-24 04:05 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/user/api/UserController.java
> +        .status(HttpStatus.CREATED)
컨트롤러 코드를 깔끔하게 유지할 수 있다는 점에서 장점이 큰 것 같아서 우선은 적용해보겠습니다..!

2024-04-26 05:28 UTC, mongmeo-dev requested changes
리뷰 한 번 더..! 확인부탁드려요~

2024-04-26 05:28 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/server/domain/auth/jwt/JwtTokenProvider.java
> +  }
요걸 PostConstruct에서 진행하는 이유가 있으신가용?

2024-04-26 05:28 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/server/domain/user/api/UserController.java
> +  public SuccessResponse<LoginResponse> login(
요거 실재론 CREATED로 안 나갈 거 같아요!

2024-04-26 05:28 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/server/domain/user/entity/User.java
> +  }
아뇽, authProvider와 socialId를 가지는 별도의 테이블이 있으면 좋겠다는 이야기였어요!

2024-04-26 05:28 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/server/domain/user/repository/UserCommandQueryRepository.java
> +public interface UserCommandQueryRepository extends UserCommandRepository, UserQueryRepository {
`{Command|Query}{Domain}Repository` 형태로 갔으면 합니다~
Command, Query를 합성하지도 않았으면 해요! 이러면 나누는 의미가 없어져요ㅠㅠ

2024-04-26 05:28 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/server/domain/user/repository/UserQueryRepositoryImpl.java
> +public class UserQueryRepositoryImpl implements UserQueryRepository {
`~Impl`은 최대한 지양해주세욤~

2024-04-26 05:28 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/server/domain/user/usecase/command/impl/UserAuthInteractor.java
> +public class UserAuthInteractor implements UserAuthUseCase {
`Interactor`는 어디서 따오신 네이밍일까용??
다른 곳에서 `Service`를 쓰고 있는데, 통일됐으면 합니다~

2024-04-26 05:28 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/server/domain/user/usecase/command/impl/UserAuthInteractor.java
> +    }
`catch`문 내에서 도메인 로직 실행하지 말아주세요! 예외처리만 부탁드려용
아예 `try-catch`를 빼고
`userRepository.findBySocialIdAndAuthProviderAndNotDeleted(userinfo.socialId(), userinfo.authProvider()).orElseGet(() -> joinNewUser(userinfo));` 로 처리하심이 좋아보입니다~

코드의 중복을 줄이는 것도 좋은데, 불필요하게 예외처리를 하게 하는 건 지양하셨음 해요~
`catch`문 내에서 에러를 전혀 핸들링하지 않고 있기도 하구요. 요건 안티패턴이에요~

2024-04-26 05:36 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/auth/jwt/JwtTokenProvider.java
> +  }
다시 읽으니 `JWT_SECRET`을 다른 데서 암호화하고 있네요?
쓸모없는 로직인 것 같아 지우겠습니다..!

2024-04-26 05:38 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/user/api/UserController.java
> +  public SuccessResponse<LoginResponse> login(
네 맞아요 ㅠㅠ 그냥 CREATED의 HTTP 응답 코드 값만 하나의 필드로 나가겠네요..!
그렇다면 ResponseEntity로 감싸서 created를 찍어야 할 것 같습니다.

2024-04-26 05:40 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/user/entity/User.java
> +  }
아, 그러면 소셜 보안과 관련한 엔티티를 따로 정의하고,
User에서 OneToOne으로 연결해 쓰라는 것으로 이해하겠습니다!

2024-04-26 06:47 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/user/repository/UserCommandQueryRepository.java
> +public interface UserCommandQueryRepository extends UserCommandRepository, UserQueryRepository {
네 알겠습니다! 
다만, `Artist`도 `CommandQueryRepository`를 가지고 있어서 이 부분도 나중에 제거하도록 하겠습니다!

2024-04-26 07:02 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/user/usecase/command/impl/UserAuthInteractor.java
> +public class UserAuthInteractor implements UserAuthUseCase {
`Interactor`는 추상화 서비스를 `usecase`로 suffix를 지어달라고 하셔서 찾아봤더니,
`usecase`의 구현을 `interactor`로 명명하기에 써봤습니다!
그러면 {추상화, 구현체}를 {`usecase`, `service`}로 지어서 사용하겠습니다!

2024-04-26 07:51 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/user/repository/UserQueryRepositoryImpl.java
> +public class UserQueryRepositoryImpl implements UserQueryRepository {
네! 전에 말씀하신 대로 수정했습니다!

2024-04-27 10:19 UTC, mongmeo-dev approved these changes
ㅋㅋㅋ첫 호흡을 너무 길게 가져가서 힘드셨을텐데, 잘 따라와주셔서 감사합니다~! 화이팅입니다~!
LGTM!

2024-04-28 11:47 UTC, jinkonu commented
감사합니다~~~

2024-04-28 11:48 UTC, merged