Spring Security 기반 인가 개발
project-lyrics/api-server pull request #7
Opened 2024-05-01 05:47 UTC by jinkonu

# 🔥 Task
- `SecurityConfig` 구성 및 구성에 필요한 `Filter`, `AuthenticationEntryPoint` 구현
- `UserController`에 있던 인증 관련 컨트롤러 메서드를 `AuthController`로 이전
- `auth` 패키지 내 구조 정리

&nbsp;
&nbsp;

> PR 타이틀에 걸맞지 않은 수정사항이 여럿 있었습니다.
이에 대해 양해의 말씀 드리겠습니다 🥹🥹

2024-05-06 20:43 UTC, mongmeo-dev requested changes
수고하셨습니다~!
이번엔 리뷰 남길 것이 거의 없네요!!
리뷰 확인해주세요~

2024-05-06 20:43 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/server/domain/auth/authentication/CustomJwtAuthenticationEntryPoint.java
> +public class CustomJwtAuthenticationEntryPoint implements AuthenticationEntryPoint {
네이밍을 할 때에, 헷갈릴만한 요소는 아예 빼버리시는 것이 좋아요!
이 클래스의 경우 `Custom` prefix가 이에 해당하는데요, Custom한 JWT를 사용하는 것인지, Custome한 JWTAuthenticationEntryPoint를 사용하는 것인지 헷갈릴만한 네이밍이에요.
그리고 사실 의미도 없구요.

2024-05-06 20:43 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/server/domain/auth/authentication/CustomJwtAuthenticationEntryPoint.java
> +    response.setCharacterEncoding("UTF-8");
`StandardCharsets.UTF_8.name()` 사용해주세요~
요런 건 일반 리터럴을 그대로 사용하지 않았으면 합니다!

2024-05-06 20:43 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/server/domain/auth/authentication/JwtAuthenticationFilter.java
> +  }
요 맥락은 아래 `getAuthorizationAccessToken(HttpServletRequest request)` method로 들어가도 될 것 같아요!
메서드 크기에 초점을 맞추시기 보다는 맥락별로 나누시는 것을 추천드려요~

ps. `isContainsAccessToken(...)` 메서드는 `Optional.ofNullable(request.getHeader(AUTHORIZATION)).filter(t -> t.startWith(TOKEN_PREFIX)).orElse(null)`로 대체할 수 있을 것 같아요~

2024-05-06 20:43 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/server/domain/user/usecase/command/impl/UserAuthService.java
> +        .orElseGet(() -> joinNewUser(userinfo));
`orElseGet()`과 `orElse()`의 차이점에 대해 보시고 더 적합한 것을 사용하시면 좋을 것 같아요~

2024-05-07 10:46 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/auth/authentication/CustomJwtAuthenticationEntryPoint.java
> +public class CustomJwtAuthenticationEntryPoint implements AuthenticationEntryPoint {
네 네이밍의 관점에서 `Custom`은 필요없는 prefix인 것 같습니다!
지워서 반영하겠습니다!

2024-05-07 10:46 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/auth/authentication/CustomJwtAuthenticationEntryPoint.java
> +    response.setCharacterEncoding("UTF-8");
네 수정해서 반영하겠습니다 !!

2024-05-07 10:47 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/auth/authentication/JwtAuthenticationFilter.java
> +  }
추신 참고해서 작성완료했습니다!
다만, `null` 반환 대신 JwtValidationException 던지도록 수정했습니다!

2024-05-07 10:48 UTC, jinkonu commented on src/main/java/com/projectlyrics/server/domain/user/usecase/command/impl/UserAuthService.java
> +        .orElseGet(() -> joinNewUser(userinfo));
네!
`orElse()`의 경우에는 `null` 여부에 관계없이 인자 메서드가 호출된다고 하여
`orElseGet()`을 유지했습니다 !!

2024-05-08 06:45 UTC, mongmeo-dev approved these changes
LGTM!

2024-05-08 08:11 UTC, merged